spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codestatus
    driver-class-name: org.postgresql.Driver
    username: codestatus
    password: 114514
  mvc:
    log-request-details: true
  application:
    name: codestatus

logging:
  level:
    web: debug

github:
  secret: d31047e36443a9340267a0f139d5a12b79539c6c
