spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/codestatus
    username: codestatus
    password: 114514
  datasource:
    url: jdbc:postgresql://localhost:5432/codestatus
    driver-class-name: org.postgresql.Driver
    username: codestatus
    password: 114514
  mvc:
    log-request-details: true
  application:
    name: codestatus
  jpa:
    show-sql: true
  data:
    redis:
      repositories:
        enabled: false
      url: redis://127.0.0.1:6379
  graphql:
    graphiql:
      enabled: true

logging:
  level:
    web: debug
    tech.archlinux.codestatus: debug

github:
  webhook-secret: 1
  client-secret: 9274fc5406c9530d103371f2c44edf1f4fe0a596
  debug: false
